name = "REFPROPwrap"
uuid = "f19ef58b-f054-4193-87d6-3496d173c75d"
authors = ["aaditya saikiran pegallapati"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
